pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm -u root install'
                sh 'npm -u root start'
            }
        }
        stage('Test'){
            steps {
                sh './jenkins/scripts/test.sh'   
            }    
        }    
        stage('Deliver'){
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finalizou? (Click "Proced" para continuar)'
                sh'./jenkins/scripts/kill.sh'
            }    
        }    
    }
}
